### PR TITLE
Restore session

### PR DESCRIPTION
**Pull request by ricdodds**
The goal of this PR is to allow users to restore old sessions so that they can keep working on them. All the changes are related with the ImageJ plugin and there's a corresponding PR on the ImPartial-Cloud repo.
* Once the `request server` checkbox is selected, users will be able to select an old session or start a new one.
* Sessions can be selected from the Server panel.
* Once the server is running users can switch between any existing session.

### CODE REVIEW

**Comment by gunjan-sh** [comment]
Facing these issues at the first run of testing the plugin on this PR: 

1. No. of channels are not loading correctly for 2 channel image. This is the dataset which is on github (vectra_2ch)
2. The Train button starts the training but once you stop the training, doesn't restart the training. 
3. The user restore session hangs the plugin if there is an internal error during the session.

**Comment by ricdodds** [comment]
The merge order is incorrect and introduced conflicts where there shouldn't be any... @gunjan-sh please check if you're not sure how to merge PRs

**Comment by gunjan-sh** [comment]
@ricdodds Please address the following issues;

Upload Model issue: While uploading the the model, getting timeout error. 

Dataset : Vectra2CH_tiff 
Model used : Trained a Model on Vectra2CH_tiff dataset, downloaded the model, tried uploading the same model on a different user session with the same Vectra2CH_tiff dataset. 

Screen Shot 2023-05-25 at 4 52 19 PM

**Comment by gunjan-sh** [comment]
Time Extension issue: 

After the session ending Warning Window Pop-up , Pressed Extend, after that plugin gives "internal error". The session becomes  inactive. Tried restoring the session after re-starting and re-login plugin. Gives the same error. The complete user session is not restorable. 

Screen Shot 2023-05-25 at 9 05 04 PM

**Comment by ricdodds** [comment]
> @ricdodds Please address the following issues;
> 
> Upload Model issue: While uploading the the model, getting timeout error.
> 
> Dataset : Vectra2CH_tiff Model used : Trained a Model on Vectra2CH_tiff dataset, downloaded the model, tried uploading the same model on a different user session with the same Vectra2CH_tiff dataset.
> 
> Screen Shot 2023-05-25 at 4 52 19 PM

Hi @gunjan-sh , thanks for pointing these out. This commit https://github.com/nadeemlab/ImPartial/pull/20/commits/bf836e5e27cff4246a1e50b1314995612eaa562e should address this first issues. Just increased the http clients timeouts.

I also increased the idle timeout of the application load balancer in front of the proxy api from 60 to 120 secs. Here the corresponding commit https://github.com/nadeemlab/ImPartial-Cloud/pull/3/commits/ebc0a8ae7aa6762ab0ebae875321375fb7ec9559

**Comment by ricdodds** [comment]
> Time Extension issue:
> 
> After the session ending Warning Window Pop-up , Pressed Extend, after that plugin gives "internal error". The session becomes inactive. Tried restoring the session after re-starting and re-login plugin. Gives the same error. The complete user session is not restorable.
> 
> Screen Shot 2023-05-25 at 9 05 04 PM

And this commit https://github.com/nadeemlab/ImPartial/pull/20/commits/39f9b11fed9d6b3fe0816d6291593790c1e70ec5 should fix this issues together with a corresponding commit on the cloud deployment https://github.com/nadeemlab/ImPartial-Cloud/pull/3/commits/1bfe41b17bcd9c5191210b77bda7378bc832c4d3

**Review by gunjan-sh — APPROVED** [review]
looks good

**Pull request merged**
